### ISSUE TITLE
Support for test files in src/test/java

### ISSUE THREAD

**Issue by pnsantos** [marcelobusico/jbehave-netbeans-plugin#2]
I was wondering if was possible to also include `src/test/java` for step implementation classes.

My project runs the tests as part of the integration-test phase which means all step implementations are in `src/test/java`

**Comment by marcelobusico** [comment]
Resolved by PR #3. New version was uploaded at http://plugins.netbeans.org/plugin/50532.

Thanks a lot for your contribution @pnsantos.
